version: "3.9"
services:
    bot:
        build:  .
        container_name: "bot"
        ports:
            - "8000:8000"
        restart: "always"
        stop_signal: SIGINT
        volumes:
            # Путь к .env файлу с настройками
            - "./.env:/app/.env"


